# Generated by Django 6.1.1 on 2026-09-07 14:57

import django.db.models.functions.text
import report.crypto_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instansi',
            name='no_wa',
            field=report.crypto_fields.EncryptedCharField(blank=True, verbose_name='No. WA/Telp'),
        ),
        migrations.AlterField(
            model_name='kunjungan',
            name='catatan',
            field=report.crypto_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kunjungan',
            name='no_wa',
            field=report.crypto_fields.EncryptedCharField(blank=True, verbose_name='No. WA/Telp'),
        ),
        migrations.AddConstraint(
            model_name='instansi',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nama'), name='uniq_instansi_nama_ci'),
        ),
    ]
